"""Read-only v1 wire columns and FK references; no database initialization.

Mirrors the frozen canonical/reconciliation DDL. Tests compare the source DDL
statically, without executing SQL. A changed wire schema requires review.
"""
from app_core.canonical_schema import CANONICAL_PRIMARY_KEYS

COLUMNS = {'prospective_calibration': ('calibration_id',
                             'sport',
                             'market_family',
                             'calibration_version',
                             'model_id',
                             'fit_start',
                             'fit_end',
                             'method',
                             'created_at',
                             'available_at',
                             'artifact_hash',
                             'payload',
                             'payload_hash'),
 'prospective_calibration_result': ('calibration_id', 'result_id'),
 'prospective_close': ('close_id',
                       'event_id',
                       'sport',
                       'market_family',
                       'selection',
                       'line',
                       'american_odds',
                       'decimal_odds',
                       'sportsbook',
                       'close_timestamp',
                       'close_source',
                       'close_verified',
                       'source_id',
                       'source_hash',
                       'raw_source',
                       'payload',
                       'payload_hash'),
 'prospective_deployment_review': ('deployment_id',
                                   'artifact_id',
                                   'validation_plan_id',
                                   'sport',
                                   'market_family',
                                   'validation_id',
                                   'deployment_state',
                                   'reviewer_id',
                                   'reviewed_at',
                                   'payload',
                                   'payload_hash'),
 'prospective_event': ('event_id',
                       'sport',
                       'game_id',
                       'provider_namespace',
                       'provider_event_id',
                       'home_team',
                       'away_team',
                       'home_team_id',
                       'away_team_id',
                       'scheduled_start',
                       'observed_at',
                       'ingested_at',
                       'source_id',
                       'source_hash',
                       'raw_source',
                       'payload',
                       'payload_hash'),
 'prospective_football_coverage': ('coverage_id',
                                   'capture_run_id',
                                   'sport',
                                   'game_id',
                                   'provider_event_id',
                                   'regular_season_target',
                                   'status',
                                   'spread_status',
                                   'total_status',
                                   'observed_at',
                                   'source_hash',
                                   'raw_source',
                                   'payload',
                                   'payload_hash'),
 'prospective_football_cycle_coverage': ('coverage_id',
                                         'capture_run_id',
                                         'sport',
                                         'observed_at',
                                         'target_games',
                                         'requested_slate_success',
                                         'source_hash',
                                         'raw_source',
                                         'payload',
                                         'payload_hash'),
 'prospective_football_event': ('version_id',
                                'game_id',
                                'sport',
                                'season',
                                'week',
                                'season_type',
                                'provider_namespace',
                                'provider_event_id',
                                'home_team',
                                'away_team',
                                'home_team_id',
                                'away_team_id',
                                'scheduled_start',
                                'neutral_site',
                                'venue',
                                'discovered_at',
                                'identity_mapping_version',
                                'source_hash',
                                'raw_source',
                                'payload',
                                'payload_hash'),
 'prospective_football_quote': ('quote_id',
                                'game_id',
                                'event_version_id',
                                'sport',
                                'market_family',
                                'selection',
                                'line',
                                'american_odds',
                                'decimal_odds',
                                'sportsbook',
                                'provider',
                                'provider_event_id',
                                'odds_event_id',
                                'observed_at',
                                'provider_last_update',
                                'capture_run_id',
                                'identity_mapping_hash',
                                'capture_horizon',
                                'minutes_to_start',
                                'quote_verified',
                                'source_hash',
                                'raw_source',
                                'payload',
                                'payload_hash'),
 'prospective_football_result': ('result_id',
                                 'game_id',
                                 'event_version_id',
                                 'sport',
                                 'result_source',
                                 'result_source_event_id',
                                 'home_score',
                                 'away_score',
                                 'observed_at',
                                 'available_at',
                                 'result_status',
                                 'source_hash',
                                 'raw_source',
                                 'payload',
                                 'payload_hash'),
 'prospective_football_settlement': ('settlement_id',
                                     'quote_id',
                                     'result_id',
                                     'game_id',
                                     'sport',
                                     'market_family',
                                     'selection',
                                     'line',
                                     'outcome',
                                     'settled_at',
                                     'settlement_version',
                                     'payload',
                                     'payload_hash'),
 'prospective_football_team_identity': ('identity_id',
                                        'sport',
                                        'canonical_team_id',
                                        'provider_namespace',
                                        'provider_team_id',
                                        'canonical_name',
                                        'provider_name',
                                        'aliases',
                                        'mapping_version',
                                        'verified_at',
                                        'mapping_source',
                                        'source_hash',
                                        'raw_source',
                                        'payload',
                                        'payload_hash'),
 'prospective_football_theover': ('research_row_id',
                                  'source_filename',
                                  'source_file_hash',
                                  'source_hash',
                                  'source_row_number',
                                  'ingested_at',
                                  'sport',
                                  'matchup',
                                  'selection',
                                  'line',
                                  'win_probability',
                                  'model_hit_rate',
                                  'matched_game_id',
                                  'match_status',
                                  'raw_source',
                                  'payload',
                                  'payload_hash'),
 'prospective_football_training_row': ('training_row_id',
                                       'quote_id',
                                       'result_id',
                                       'settlement_id',
                                       'game_id',
                                       'sport',
                                       'market_family',
                                       'label',
                                       'training_row_status',
                                       'blockers',
                                       'available_for_training_at',
                                       'source_manifest_hash',
                                       'payload',
                                       'payload_hash'),
 'prospective_model': ('model_id',
                       'sport',
                       'market_family',
                       'model_version',
                       'training_start',
                       'training_cutoff',
                       'training_observation_count',
                       'independent_event_count',
                       'feature_version',
                       'training_code_commit',
                       'created_at',
                       'available_at',
                       'artifact_hash',
                       'payload',
                       'payload_hash'),
 'prospective_model_training_result': ('model_id', 'result_id'),
 'prospective_prediction': ('observation_id',
                            'event_id',
                            'sport',
                            'market_family',
                            'selection',
                            'quote_id',
                            'model_id',
                            'model_version',
                            'model_trained_through',
                            'model_available_at',
                            'feature_version',
                            'feature_snapshot_id',
                            'feature_frozen_at',
                            'calibration_id',
                            'calibration_version',
                            'calibration_available_at',
                            'policy_version',
                            'prediction_timestamp',
                            'mean_probability',
                            'conservative_probability',
                            'push_probability',
                            'loss_probability',
                            'probability_semantics',
                            'evidence_snapshot_id',
                            'evidence_hash',
                            'runtime_hash',
                            'source_commit',
                            'payload',
                            'payload_hash'),
 'prospective_quote': ('quote_id',
                       'event_id',
                       'sport',
                       'market_family',
                       'selection',
                       'line',
                       'american_odds',
                       'decimal_odds',
                       'sportsbook',
                       'quote_timestamp',
                       'quote_source',
                       'quote_verified',
                       'source_id',
                       'source_hash',
                       'raw_source',
                       'payload',
                       'payload_hash'),
 'prospective_reconciled_fact': ('fact_id',
                                 'sport',
                                 'market_family',
                                 'canonical_identity',
                                 'capture_signature',
                                 'source_key',
                                 'payload',
                                 'payload_hash'),
 'prospective_reconciled_source': ('source_key',
                                   'sport',
                                   'source_table',
                                   'source_record_id',
                                   'source_hash',
                                   'raw_source',
                                   'payload',
                                   'payload_hash'),
 'prospective_result': ('result_id',
                        'event_id',
                        'sport',
                        'market_family',
                        'selection',
                        'result_source',
                        'result_source_id',
                        'observed_at',
                        'available_at',
                        'home_score',
                        'away_score',
                        'outcome',
                        'grading_version',
                        'revises_result_id',
                        'source_hash',
                        'raw_source',
                        'payload',
                        'payload_hash'),
 'prospective_validation_artifact': ('artifact_id',
                                     'validation_plan_id',
                                     'sport',
                                     'market_family',
                                     'created_at',
                                     'status',
                                     'report_hash',
                                     'payload',
                                     'payload_hash'),
 'prospective_validation_plan': ('validation_plan_id',
                                 'sport',
                                 'market_family',
                                 'version',
                                 'supersedes_plan_id',
                                 'model_id',
                                 'calibration_id',
                                 'training_cutoff',
                                 'validation_start',
                                 'validation_end',
                                 'holdout_start',
                                 'holdout_end',
                                 'minimum_independent_sample',
                                 'minimum_effective_sample',
                                 'frozen_at',
                                 'artifact_hash',
                                 'payload',
                                 'payload_hash')}

DEPENDENCIES = {'prospective_calibration': (('model_id', 'prospective_model', 'model_id'),),
 'prospective_calibration_result': (('calibration_id', 'prospective_calibration', 'calibration_id'),
                                    ('result_id', 'prospective_result', 'result_id')),
 'prospective_close': (('event_id', 'prospective_event', 'event_id'),),
 'prospective_deployment_review': (('artifact_id', 'prospective_validation_artifact', 'artifact_id'),
                                   ('validation_plan_id',
                                    'prospective_validation_plan',
                                    'validation_plan_id')),
 'prospective_football_quote': (('event_version_id', 'prospective_football_event', 'version_id'),),
 'prospective_football_result': (('event_version_id', 'prospective_football_event', 'version_id'),),
 'prospective_football_settlement': (('quote_id', 'prospective_football_quote', 'quote_id'),
                                     ('result_id', 'prospective_football_result', 'result_id')),
 'prospective_football_training_row': (('quote_id', 'prospective_football_quote', 'quote_id'),
                                       ('result_id', 'prospective_football_result', 'result_id'),
                                       ('settlement_id', 'prospective_football_settlement', 'settlement_id')),
 'prospective_model_training_result': (('model_id', 'prospective_model', 'model_id'),
                                       ('result_id', 'prospective_result', 'result_id')),
 'prospective_prediction': (('event_id', 'prospective_event', 'event_id'),
                            ('quote_id', 'prospective_quote', 'quote_id'),
                            ('model_id', 'prospective_model', 'model_id'),
                            ('calibration_id', 'prospective_calibration', 'calibration_id')),
 'prospective_quote': (('event_id', 'prospective_event', 'event_id'),),
 'prospective_reconciled_fact': (('source_key', 'prospective_reconciled_source', 'source_key'),),
 'prospective_result': (('event_id', 'prospective_event', 'event_id'),
                        ('revises_result_id', 'prospective_result', 'result_id')),
 'prospective_validation_artifact': (('validation_plan_id',
                                      'prospective_validation_plan',
                                      'validation_plan_id'),),
 'prospective_validation_plan': (('supersedes_plan_id', 'prospective_validation_plan', 'validation_plan_id'),
                                 ('model_id', 'prospective_model', 'model_id'),
                                 ('calibration_id', 'prospective_calibration', 'calibration_id'))}

SCHEMA = {table: (cols, CANONICAL_PRIMARY_KEYS[table]) for table, cols in COLUMNS.items()}
