# Hardcoded Global Weights for Probability Blending
# Two-tier system: Kalshi-heavy when Kalshi agrees, fallback when it doesn't

# Tier 1: Kalshi agrees (prob >= 55% for pick side)
KALSHI_WEIGHT = 0.475      # Prediction markets highest signal
MARKET_WEIGHT = 0.20      # Bookmaker odds
ML_MODEL_WEIGHT = 0.15    # Historical model
THEOVER_WEIGHT = 0.125     # TheOver consensus
SENTIMENT_WEIGHT = 0.05   # News sentiment

# Market Maturity Overrides (MLB/NHL)
LOW_LIQUIDITY_KALSHI_WEIGHT = 0.30
LOW_LIQUIDITY_ML_MODEL_WEIGHT = 0.35

# Tier 2: Fallback weights (Kalshi disagrees or unavailable)
FALLBACK_MARKET_WEIGHT = 0.35
FALLBACK_ML_WEIGHT = 0.35
FALLBACK_THEOVER_WEIGHT = 0.20
FALLBACK_SENTIMENT_WEIGHT = 0.10

# Baseline Thresholds
BASELINE_MIN_EV = 0.01
BASELINE_MIN_EDGE = 0.02

# Stricter Total Over Thresholds
TOTAL_OVER_MIN_EV = 0.03
TOTAL_OVER_MIN_EDGE = 0.04

# NBA Star-Active Adjustments
NBA_STAR_ACTIVE_TOTAL_OVER_BOOST = 0.01
NBA_STAR_ACTIVE_TOTAL_UNDER_PENALTY = -0.01

# Total Win Probability Floors
TOTAL_MIN_WIN_PROB = 0.56
TOTAL_UNDER_MIN_WIN_PROB = 0.62
TOTAL_UNDER_MIN_EV = 0.18
TOTAL_UNDER_MIN_EDGE = 0.10
NHL_TOTAL_EXTRA_EDGE_PENALTY = 0.01
NHL_TOTAL_MIN_WIN_PROB = 0.57
NHL_TOTAL_MIN_WIN_PROB_STRICT = 0.58
NBA_TOTAL_MIN_WIN_PROB = 0.58
NBA_TOTAL_MIN_EV = 0.01
NBA_TOTAL_MIN_EDGE = 0.02
NHL_TOTAL_MIN_EV_STRICT = 0.01
NHL_TOTAL_MIN_EDGE_STRICT = 0.02
FALLBACK_HEAVY_TOTAL_EV_MULTIPLIER = 0.85

# Spread Divergence Overrides (for ML vs Kalshi diff > 20%)
SPREAD_DIVERGENCE_OVERRIDE_MIN_PROB = 0.55
SPREAD_DIVERGENCE_OVERRIDE_MIN_EV = 0.03
SPREAD_DIVERGENCE_OVERRIDE_MIN_EDGE = 0.04
DIVERGENCE_HIGH_VARIANCE_MIN_EV = 0.00
DIVERGENCE_HIGH_VARIANCE_MIN_EDGE = 0.00
DIVERGENCE_HIGH_VARIANCE_MIN_PROB = 0.50

# Side Minimum Win Probability
SIDE_MIN_WIN_PROB = 0.52
MLB_SPREAD_MIN_WIN_PROB = 0.53
MLB_SPREAD_ACTIONABLE_BONUS = 0.00
MLB_SPREAD_EXTRA_ACTIONABLE_PENALTY = 0.01
MLB_SPREAD_ACTIONABLE_PENALTY = 0.03
MLB_SPREAD_FINALIST_SCORE_PENALTY = 0.05
NBA_SIDE_ACTIONABLE_BONUS = 0.01
NBA_OVER_ACTIONABLE_BONUS = 0.01
MLB_OVER_ACTIONABLE_MIN_PROB = 0.57
MLB_OVER_ACTIONABLE_MIN_EV = 0.03
MLB_OVER_ACTIONABLE_MIN_EDGE = 0.04

# Cold-Market Penalty Layer (by League + Market Type)
MLB_TOTAL_OVER_ACTIONABLE_PENALTY = 0.00
MLB_TOTAL_UNDER_ACTIONABLE_PENALTY = 0.03
NBA_TOTAL_OVER_ACTIONABLE_PENALTY = 0.01
NBA_TOTAL_UNDER_ACTIONABLE_PENALTY = 0.02
NHL_TOTAL_OVER_ACTIONABLE_PENALTY = 0.02
NHL_TOTAL_UNDER_ACTIONABLE_PENALTY = 0.03

# No-Kalshi totals are treated as lower confidence in selection stage
NO_KALSHI_TOTAL_EXTRA_PENALTY = 0.02
NO_KALSHI_TOTAL_UNDER_EXTRA_PENALTY = 0.03

# Cross-family selection nudge to avoid unders dominating finalists on EV/edge alone
TOTAL_UNDER_FINALIST_SCORE_PENALTY = 0.10

# Static empirical hooks (league + family) for later recap-driven calibration.
# Values are additive threshold bumps applied to both EV and edge in selection gating.
LEAGUE_MARKET_FAMILY_ACTIONABLE_PENALTIES = {
    ("MLB", "over"): 0.01,
    ("MLB", "under"): 0.01,
    ("MLB", "side"): 0.00,
    ("NBA", "over"): 0.00,
    ("NBA", "under"): 0.01,
    ("NBA", "side"): 0.00,
    ("NHL", "over"): 0.01,
    ("NHL", "under"): 0.02,
    ("NHL", "side"): 0.00,
}

# Model-health guardrail for noisy slates
FALLBACK_HEAVY_TOTAL_EXTRA_PENALTY = 0.01

# Profiles
BEST_PICKS_PROFILE = 'STANDARD'

# Consensus-aware Actionable overlays
NEUTRAL_ACTIONABLE_MIN_PROB = 0.58
NEUTRAL_ACTIONABLE_MIN_EV = 0.03
NEUTRAL_ACTIONABLE_MIN_EDGE = 0.04

DISAGREES_ACTIONABLE_MIN_PROB = 0.60
DISAGREES_ACTIONABLE_MIN_EV = 0.04
DISAGREES_ACTIONABLE_MIN_EDGE = 0.05

# Line Locking Configuration
LOCK_UPLOAD_LINES_FOR_MATCHED_ROWS = False
ALLOW_UPLOAD_TOTAL_FALLBACK_ACTIONABLE = False

# Production-card calibration guards (totals concentration + overconfidence control)
MAX_TOTAL_OVER_ACTIONABLE_SHARE = 0.60
MAX_TOTAL_OVER_ACTIONABLE_COUNT = 4
MAX_MLB_TOTAL_OVER_ACTIONABLE_COUNT = 3
TOTAL_OVER_PROB_SHRINK = 0.60
MLB_TOTAL_OVER_PROB_SHRINK = 0.50
MLB_TOTAL_OVER_MIN_PRODUCTION_WIN_PROB = 0.62
MLB_TOTAL_OVER_MIN_PRODUCTION_EV = 0.08
MLB_TOTAL_OVER_MIN_PRODUCTION_EDGE = 0.06
DEGRADED_FEATURE_KELLY_MULTIPLIER = 0.50
DEGRADED_FEATURE_MAX_SLATE_EXPOSURE_PCT = 0.12
DEGRADED_FEATURE_MAX_PICK_EXPOSURE_PCT = 0.02
ALLOW_EMPTY_CARD_RECOVERY = False
