# Hardcoded Global Weights for Probability Blending
# Two-tier system: Kalshi-heavy when Kalshi agrees, fallback when it doesn't

# Tier 1: Kalshi agrees (prob >= 55% for pick side)
KALSHI_WEIGHT = 0.475      # Prediction markets highest signal
MARKET_WEIGHT = 0.20      # Bookmaker odds
ML_MODEL_WEIGHT = 0.15    # Historical model
THEOVER_WEIGHT = 0.125     # TheOver consensus
SENTIMENT_WEIGHT = 0.05   # News sentiment

# Market Maturity Overrides (MLB/NHL)
LOW_LIQUIDITY_KALSHI_WEIGHT = 0.30
LOW_LIQUIDITY_ML_MODEL_WEIGHT = 0.35

# Tier 2: Fallback weights (Kalshi disagrees or unavailable)
FALLBACK_MARKET_WEIGHT = 0.35
FALLBACK_ML_WEIGHT = 0.35
FALLBACK_THEOVER_WEIGHT = 0.20
FALLBACK_SENTIMENT_WEIGHT = 0.10

# Baseline Thresholds
BASELINE_MIN_EV = 0.01
BASELINE_MIN_EDGE = 0.02

# Stricter Total Over Thresholds
TOTAL_OVER_MIN_EV = 0.03
TOTAL_OVER_MIN_EDGE = 0.04

# NBA Star-Active Adjustments
NBA_STAR_ACTIVE_TOTAL_OVER_BOOST = 0.01
NBA_STAR_ACTIVE_TOTAL_UNDER_PENALTY = -0.01

# Total Win Probability Floors
TOTAL_MIN_WIN_PROB = 0.56
NHL_TOTAL_MIN_WIN_PROB = 0.57
NHL_TOTAL_MIN_WIN_PROB_STRICT = 0.58
NBA_TOTAL_MIN_WIN_PROB = 0.58
NBA_TOTAL_MIN_EV = 0.01
NBA_TOTAL_MIN_EDGE = 0.02
NHL_TOTAL_MIN_EV_STRICT = 0.01
NHL_TOTAL_MIN_EDGE_STRICT = 0.02
FALLBACK_HEAVY_TOTAL_EV_MULTIPLIER = 0.85

# Spread Divergence Overrides (for ML vs Kalshi diff > 20%)
SPREAD_DIVERGENCE_OVERRIDE_MIN_PROB = 0.55
SPREAD_DIVERGENCE_OVERRIDE_MIN_EV = 0.03
SPREAD_DIVERGENCE_OVERRIDE_MIN_EDGE = 0.04

# Side Minimum Win Probability
SIDE_MIN_WIN_PROB = 0.52

# Consensus-aware Actionable overlays
NEUTRAL_ACTIONABLE_MIN_PROB = 0.58
NEUTRAL_ACTIONABLE_MIN_EV = 0.03
NEUTRAL_ACTIONABLE_MIN_EDGE = 0.04

DISAGREES_ACTIONABLE_MIN_PROB = 0.60
DISAGREES_ACTIONABLE_MIN_EV = 0.04
DISAGREES_ACTIONABLE_MIN_EDGE = 0.05

# Line Locking Configuration
LOCK_UPLOAD_LINES_FOR_MATCHED_ROWS = False
